### ISSUE TITLE
About defregion

### ISSUE THREAD

**Issue by ray0903** [mumax/3#264] opened 2020-06-21 07:56 UTC
if i defregion like this :  defregion(1,cuboid(5e-9,5e-9,1e-9).transl(0,0,0)) ,my simulation‘s  result will be  different with normal.  But  i think   this code is  right.

**Comment by JeroenMulkers** [comment] 2020-06-29 15:55
What do you mean by 'normal'?

Can you give a minimal script which demonstrates the problem?

**Comment by ray0903** [comment] 2020-06-30 06:59
This is my script .


SetGridSize(500, 25, 1)    
SetCellSize(2e-9,2e-9,1e-9)
outputformat = OVF2_TEXT
BFO1:= cuboid(1000e-9,50e-9,1e-9).transl(0,0,0)   
setgeom(BFO1)
defregion(1,cuboid(30e-9,50e-9,1e-9).transl(0,0,0))   
Aex=1.3e-11
Msat=800e3
GammaLL =2.21e5;
alpha=0
B_ext=vector(1.005,0,0)      
relax()
save(m)                                            
B_ext.setregion(1,vector(1.005,0.5*sin(2*pi*500e9*(t-50e-12))/(2*pi*500e9*(t-50e-12)),0)) 
autosave(m, 1e-12)
SetSolver(2)
FixDt = 1e-12
run(5e-9)

My code is used to excite spin waves locally
If I write this way, the data is wrong.But if I change the definition of region to x range, the result is correct.  Like this 
"defregion(1,Xrange(-15e-9,15e-9)) 
 The result of the two definitions should be the same in theory.

**Comment by JeroenMulkers** [comment] 2020-06-30 08:44
Using the cuboid or the xrange should indeed give the same results here. However, in both cases, the dynamics of the magnetization seems to me to be insignificant. So I do not know what to look at to compare both cases. Can you explain why you believe using xrange yields correct results while using a cuboid yields wrong results? Which quantities do we need to investigate?

Side note: I've put multiplication operators in the definition of the excitation field because otherwise the script does not run. I might have done this incorrectly which could be the reason why I do not see any significant output. Please provide a working script.

**Comment by ray0903** [comment] 2020-07-02 05:19
Hello，
   I think that's a problem with my solver selection.And  I recently had a problem about recompiling mumax3.3.10.


I've used a lot of methods, but I still can't solve it.So could you send me the latest version of mumax3.I really spent a lot of time  about recompiling this. Thank you!







At 2020-06-30 16:44:18, "Jeroen Mulkers" <notifications@github.com> wrote:

Using the cuboid or the xrange should indeed give the same results here. However, in both cases, the dynamics of the magnetization seems to me to be insignificant. So I do not know what to look at to compare both cases. Can you explain why you believe using xrange yields correct results while using a cuboid yields wrong results? Which quantities do we need to investigate?

Side note: I've put multiplication operators in the definition of the excitation field because otherwise the script does not run. I might have done this incorrectly which could be the reason why I do not see any significant output. Please provide a working script.

**Comment by JonathanMaes** [comment] 2024-10-10 16:11
I have run your example script in the latest version of mumax³, and get the exact same output .ovf files for both `XRange` and `Cuboid`. I will close this since both Jeroen and I can not reproduce this issue.

**Closed by JonathanMaes** 2024-10-10 16:11 UTC
