### ISSUE TITLE
Trouble Converting Outputs

### ISSUE THREAD

**Issue by Orange45** [mumax/3#126] opened 2017-09-14 04:22 UTC
I have tried to open .ovf's with mumax-convert.exe but the window just pops up and disappears, with no sign of anything having happened. I have tried to open mumax-convert.exe by itself to try to follow the guide here, https://godoc.org/github.com/mumax/3/cmd/mumax3-convert, but I can't seem to get any files converted.

**Comment by godsic** [comment] 2017-09-14 05:22
Mumax3-convert is a commandline utility. So it does not open any GUIs. What exactly you like to convert and to which format?

**Comment by barnex** [comment] 2017-09-14 19:26
You need to open a terminal and type the commands found in the documentation.
Closing as this is not a bug.

**Closed by barnex** 2017-09-14 19:26 UTC
