### ISSUE TITLE
Allow zoom in

### ISSUE THREAD

**Issue by deltaf** [mumax/3#49] opened 2015-10-28 20:42 UTC
It would be very helpful if we could zoom into the sample as in OOMMF.
Right now, unless the number of cells is large enough, we can't see much of the sample. I think it is 1 pixel per cell at scale=1, and for a sample 256x16, we can only see a single line of "arrows".

**Comment by syockit** [comment] 2015-10-29 03:38
Is this for the browser GUI?

**Comment by kahlos** [comment] 2015-10-29 10:33
In the browser GUI, as a workaround, I currently add a HTML "height" attribute using chrome's 'inspect element'. This way you can make the image more visible, but you're simply scaling the JPG image. A better option would be a % slider bar, which adjusts the amount of pixels per cell.

**Comment by godsic** [comment] 2015-10-29 10:42
Browsers typically use some high-order re-samples, so offloading image
scaling to the browser does makes sense to keep mumax3 free from virtually
useless code.

So adding 'transform: scale(x,x);' CSS attribute to the image output should
do the job.

Callum are you willing to implement this?


On 29 October 2015 at 11:33, Callum Vincent <notifications@github.com>
wrote:

> In the browser GUI, as a workaround, I currently add a HTML "height"
> attribute using chrome's 'inspect element'. This way you can make the image
> more visible, but you're simply scaling the JPG image. A better option
> would be a % slider bar, which adjusts the amount of pixels per cell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/49#issuecomment-152139298>.
>



-- 
 Mykola

**Comment by kahlos** [comment] 2015-10-29 10:56
I agree, CSS is the best way, I'll give it a go!

**Comment by kahlos** [comment] 2015-10-29 12:03
I've found that we can either modify the CSS in *engine/html.go* or perhaps change *engine/render.go*. 

The *transform* CSS element doesn't work as anticipated, using *height=%* seems to work better. Even this isn't working exactly how I am anticipating, a *height=8%* in the img element keeps the image size roughly the same (I would expect 100%), with values up to about 50% being a useful range to scale it bigger.

I've tried implementing a slider in the engine/html.go, which should set height between 8-50%. However, I'm not able to either compile or test on my current system. I've added the following into engine/html.go for the slider and modified the CSS as shown:

    <tr title="Zoom in small images"> <td> Zoom: {{.Range "renderZoom" 8 50 50}} </td><td> {{.Span "renderZoomLabel" "%"}}  </td></tr>
    img   { margin: 10px; width: renderZoom%; }


I'm going to leave it there for now, but it should be simple enough for someone with more experience to  add in these changes and compile/test. I'll take a look at this again in a few weeks if no-one has got anywhere.

**Comment by deltaf** [comment] 2015-10-29 15:14
Yes, for the browser GUI.

> I agree, CSS is the best way, I'll give it a go!

I disagree. Changing the image won't work because it is not going to give any new details. Actually, this can already be achieve simply by zooming into the page using browser's zoom.
With a browser-side, I still see a single line of "arrows". It's useless.

In OOMMF, you can zoom into magnetization and it gives you more details. Surely, a single cell will correspond to many pixel, let's say 16x16, but the point is it can show an arrow for each cell.

**Comment by deltaf** [comment] 2015-10-29 15:16
> so offloading image scaling to the browser does makes sense to keep mumax3 free from virtually
useless code.

A non-trivial scaling like OOMMF does cannot be achieve on the browser side.

**Comment by godsic** [comment] 2015-10-29 15:26
By design,  mumax3 tries to keep previews reasonably small to maintain GUI
responsiveness (please look @ 'engine/render.go' code).

Personally, I believe that visualization goes beyond mumax3 scope and is,
actually, something to be done using 3rd party, on-purpose made software,
e.g. https://github.com/grahamrow/Muview2 .

Anyway all the required logic is already in the mumax3 code, so feel free
to implement the requested feature.




On 29 October 2015 at 16:14, deltaf <notifications@github.com> wrote:

> Yes, for the browser GUI.
>
> I agree, CSS is the best way, I'll give it a go!
>
> I disagree. Changing the image won't work because it is not going to give
> any new details. Actually, this can already be achieve simply by zooming
> into the page using browser's zoom.
> With a browser-side, I still see a single line of "arrows". It's useless.
>
> In OOMMF, you can zoom into magnetization and it gives you more details.
> Surely, a single cell will correspond to many pixel, let's say 16x16, but
> the point is it can show an arrow for each cell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/49#issuecomment-152210586>.
>



-- 
 Mykola

**Comment by kahlos** [comment] 2015-10-29 15:26
True, it would be more useful to adjust the render's output. It would probably have to be implemented via the API, so that render output can be adjusted in a script. I guess the best place to start is *engine/render.go*.

If you weren't aware, there is software available to render and view in 3D the .ovf files, [muview](https://github.com/grahamrow/Muview2)

**Comment by deltaf** [comment] 2015-10-29 15:30
> Personally, I believe that visualization goes beyond mumax3 scope and is,

Then I don't understand why you already are doing visualization in a browser GUI with zoom out, or why you agreed doing it when the task was a simple browser-size scaling, or why you're OK with it if somebody else will implement it.

Yes, I'm aware of and using OOMMF and muview already.

Anyway, I think I'll just go back to OOMMF.

**Comment by godsic** [comment] 2015-10-29 15:39
I am not doing visualization in a browser GUI, I am not using a browser GUI
at all. I am typically doing mumax3-convert and ParaView.

Browser-side scaling is cheap in terms of the lines of code and most likely
will not break things. So it makes sense to me.

mumax3-side zoom-in does require changes to 'engine/render.go' (maybe
elsewhere as well) and, therefore, needs more efforts to implement and test.

On 29 October 2015 at 16:30, deltaf <notifications@github.com> wrote:

> Personally, I believe that visualization goes beyond mumax3 scope and is,
>
> Then I don't understand why you already are doing visualization in a
> browser GUI with zoom out, or why you agreed doing it when the task was a
> simple browser-size scaling, or why you're OK with it if somebody else will
> implement it.
>
> Yes, I'm aware of and using OOMMF and muview already.
>
> Anyway, I think I'll just go back to OOMMF.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/49#issuecomment-152215703>.
>



-- 
 Mykola

**Comment by barnex** [comment] 2017-09-25 19:09
Closing this as there are plenty of ways to 'zoom in', like mumax3-convert, various 3rd-party tools or using your browser's zoom feature.

The reason to have a 'zoom out' feature is absolute necessity. Real-time rendering of 30 megapixel images in the browser simply grinds the browser and mumax to a halt. Therefore zoom out is done on the GPU, even before the data is encoded and sent to the browser. By default, images wider than 1024 pixels are even downscaled by default, for precisely this reason.

**Closed by barnex** 2017-09-25 19:09 UTC
