### ISSUE TITLE
Problems with Energy Minimizer solver on Windows

### ISSUE THREAD

**Issue by aurehr** [mumax/3#51] opened 2015-11-02 10:24 UTC
We have a GTX Titan X running on windows 8.1 with CUDA 7.5 and updated drivers. We are unable to use the energy minimizer solver present in the 3.9c version of Mumax3. All the other modules work properly but when the minimizer starts to work the error:

CUDA_ERROR_INVALID_IMAGE appears and the simulation stops showing some panic messages.

Should be it because of the version of cuda libraries used in the windows compilation of Mumax3 (version 6.5) and the fact that the graphic board is very recent? 

Thank you.

**Comment by kahlos** [comment] 2015-11-02 10:27
We have the same problem here with a 980Ti running on windows 7, with the same drivers and mumax version. Should I try recompiling with the latest CUDA & mumax?

**Comment by godsic** [comment] 2015-11-02 10:37
mumax3, although linked against cuda6.5, uses PTX code complied with recent
versions of CUDA to properly support Maxwell-based GPUs. This weird
approach is due to the bug in cuFFT provided in CUDA7+. So I guess what
happened is that minimizer was merged after the commit where I've updated
PTX code. If somebody is willing to compile and test, I can update the
entire PTX code?



On 2 November 2015 at 11:27, Callum Vincent <notifications@github.com>
wrote:

> We have the same problem here with a 980Ti running on windows 7, with the
> same drivers and mumax version. Should I try recompiling with the latest
> CUDA & mumax?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/51#issuecomment-152981775>.
>



-- 
 Mykola

**Comment by kahlos** [comment] 2015-11-02 10:42
I'll do the compilation. I'll have a go at getting the current version compiled now on our windows machine.

**Comment by aurehr** [comment] 2015-11-02 11:29
Thank you very much kahlos. If it works please let us know.

:)

**Comment by kahlos** [comment] 2015-11-02 11:59
I'm otherwise engaged today, but with my morning I've managed to compile everything except the main mumax executable. Below is the output from the compilation. @godsic Any ideas what the problem is? Is it just the *gcc.exe: The filename or extension is too long.*? Is there an easy way to fix this?

```
F:\mumax-build>go get -u -v github.com/mumax/3/...
github.com/mumax/3 (download)
github.com/barnex/fftw (download)
github.com/barnex/matrix (download)
github.com/mumax/3/test
github.com/mumax/3/util
github.com/mumax/3/cuda/cu
github.com/mumax/3/timer
github.com/mumax/3/cuda/curand
github.com/mumax/3/freetype/raster
github.com/mumax/3/data
github.com/mumax/3/oommf
github.com/mumax/3/svgo
# github.com/mumax/3/cuda/cu
F:\mumax\src\github.com\mumax\3\cuda\cu\context.go:5:18: fatal error: cuda.h: No
 such file or directory
 //#include <cuda.h>
                  ^
compilation terminated.
github.com/mumax/3/dump
# github.com/mumax/3/cuda/curand
F:\mumax\src\github.com\mumax\3\cuda\curand\generator.go:3:20: fatal error: cura
nd.h: No such file or directory
 //#include <curand.h>
                    ^
compilation terminated.
github.com/mumax/3/gui
github.com/mumax/3/httpfs
github.com/mumax/3/mag
github.com/mumax/3/draw
github.com/mumax/3/script
github.com/mumax/3/prof
github.com/barnex/fftw/internal/double
github.com/barnex/fftw/internal/float
github.com/mumax/3/cmd/mumax3-convert
github.com/barnex/matrix
github.com/mumax/3/cmd/mumax3-httpfsd
github.com/mumax/3/cmd/mumax3-plot
github.com/mumax/3/cmd/mumax3-script
github.com/mumax/3/cmd/mumax3-server
# github.com/barnex/fftw/internal/double
F:\mumax\src\github.com\barnex\fftw\internal\double\kernel_kalloc.c: In function
 'fftw_kernel_malloc':
F:\mumax\src\github.com\barnex\fftw\internal\double\kernel_kalloc.c:91:6: warnin
g: implicit declaration of function 'memalign' [-Wimplicit-function-declaration]

      p = memalign(MIN_ALIGNMENT, n);
      ^
F:\mumax\src\github.com\barnex\fftw\internal\double\kernel_kalloc.c:91:8: warnin
g: assignment makes pointer from integer without a cast [enabled by default]
      p = memalign(MIN_ALIGNMENT, n);
        ^
# github.com/barnex/fftw/internal/float
F:\mumax\src\github.com\barnex\fftw\internal\float\kernel_kalloc.c: In function
'fftwf_kernel_malloc':
F:\mumax\src\github.com\barnex\fftw\internal\float\kernel_kalloc.c:91:6: warning
: implicit declaration of function 'memalign' [-Wimplicit-function-declaration]
      p = memalign(MIN_ALIGNMENT, n);
      ^
F:\mumax\src\github.com\barnex\fftw\internal\float\kernel_kalloc.c:91:8: warning
: assignment makes pointer from integer without a cast [enabled by default]
      p = memalign(MIN_ALIGNMENT, n);
        ^
go build github.com/barnex/fftw/internal/double: gcc: fork/exec f:\win-builds\bi
n\gcc.exe: The filename or extension is too long.
go build github.com/barnex/fftw/internal/float: gcc: fork/exec f:\win-builds\bin
\gcc.exe: The filename or extension is too long.

```

**Comment by godsic** [comment] 2015-11-02 12:06
- maybe I am wrong, but gcc should not be invoked at all. try go1.5.1.

- 'fatal error: cuda.h: No such file or directory' means go cannot find the
header file specified; look at the 'cuda/cu/cgoflags.go' file for the list
of supported CUDA paths (actually those are default paths CUDA installer
suggests). I would suggest you to use 'CUDA6.5 for Maxwell' as the only
rock solid release for Maxwell (if it is still downloadable).

On 2 November 2015 at 12:59, Callum Vincent <notifications@github.com>
wrote:

> I'm otherwise engaged today, but with my morning I've managed to compile
> everything except the main mumax executable. Below is the output from the
> compilation. @godsic <https://github.com/godsic> Any ideas what the
> problem is? Is it just the *gcc.exe: The filename or extension is too
> long.*? Is there an easy way to fix this?
>
> F:\mumax-build>go get -u -v github.com/mumax/3/...github.com/mumax/3 (download)github.com/barnex/fftw (download)github.com/barnex/matrix (download)github.com/mumax/3/testgithub.com/mumax/3/utilgithub.com/mumax/3/cuda/cugithub.com/mumax/3/timergithub.com/mumax/3/cuda/curandgithub.com/mumax/3/freetype/rastergithub.com/mumax/3/datagithub.com/mumax/3/oommfgithub.com/mumax/3/svgo
> # github.com/mumax/3/cuda/cu
> F:\mumax\src\github.com\mumax\3\cuda\cu\context.go:5:18: fatal error: cuda.h: No
>  such file or directory
>  //#include <cuda.h>
>                   ^
> compilation terminated.github.com/mumax/3/dump
> # github.com/mumax/3/cuda/curand
> F:\mumax\src\github.com\mumax\3\cuda\curand\generator.go:3:20: fatal error: cura
> nd.h: No such file or directory
>  //#include <curand.h>
>                     ^
> compilation terminated.github.com/mumax/3/guigithub.com/mumax/3/httpfsgithub.com/mumax/3/maggithub.com/mumax/3/drawgithub.com/mumax/3/scriptgithub.com/mumax/3/profgithub.com/barnex/fftw/internal/doublegithub.com/barnex/fftw/internal/floatgithub.com/mumax/3/cmd/mumax3-convertgithub.com/barnex/matrixgithub.com/mumax/3/cmd/mumax3-httpfsdgithub.com/mumax/3/cmd/mumax3-plotgithub.com/mumax/3/cmd/mumax3-scriptgithub.com/mumax/3/cmd/mumax3-server
> # github.com/barnex/fftw/internal/double
> F:\mumax\src\github.com\barnex\fftw\internal\double\kernel_kalloc.c: In function
>  'fftw_kernel_malloc':
> F:\mumax\src\github.com\barnex\fftw\internal\double\kernel_kalloc.c:91:6: warnin
> g: implicit declaration of function 'memalign' [-Wimplicit-function-declaration]
>
>       p = memalign(MIN_ALIGNMENT, n);
>       ^
> F:\mumax\src\github.com\barnex\fftw\internal\double\kernel_kalloc.c:91:8: warnin
> g: assignment makes pointer from integer without a cast [enabled by default]
>       p = memalign(MIN_ALIGNMENT, n);
>         ^
> # github.com/barnex/fftw/internal/float
> F:\mumax\src\github.com\barnex\fftw\internal\float\kernel_kalloc.c: In function
> 'fftwf_kernel_malloc':
> F:\mumax\src\github.com\barnex\fftw\internal\float\kernel_kalloc.c:91:6: warning
> : implicit declaration of function 'memalign' [-Wimplicit-function-declaration]
>       p = memalign(MIN_ALIGNMENT, n);
>       ^
> F:\mumax\src\github.com\barnex\fftw\internal\float\kernel_kalloc.c:91:8: warning
> : assignment makes pointer from integer without a cast [enabled by default]
>       p = memalign(MIN_ALIGNMENT, n);
>         ^
> go build github.com/barnex/fftw/internal/double: gcc: fork/exec f:\win-builds\bi
> n\gcc.exe: The filename or extension is too long.
> go build github.com/barnex/fftw/internal/float: gcc: fork/exec f:\win-builds\bin
> \gcc.exe: The filename or extension is too long.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/51#issuecomment-152998450>.
>



-- 
 Mykola

**Comment by kahlos** [comment] 2015-11-02 12:12
I do have go1.5.1 installed and running. As far as I can tell, gcc is invoked to compile the fftw code; it is listed as a dependency in the 'releases' section.

I'll take a look at the cgoflags as you suggest and try CUDA6.5 if I have any more problems.

**Comment by godsic** [comment] 2015-11-02 12:16
Then I would suggest you to check your mingw installation. 'memalign'
function is a part of stdlib for a while, so it should not trigger any
problems.

On 2 November 2015 at 13:12, Callum Vincent <notifications@github.com>
wrote:

> I do have go1.5.1 installed and running. As far as I can tell, gcc is
> invoked to compile the fftw code; it is listed as a dependency in the
> 'releases' section.
>
> I'll take a look at the cgoflags as you suggest and try CUDA6.5 if I have
> any more problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/51#issuecomment-153000263>.
>



-- 
 Mykola

**Comment by godsic** [comment] 2015-11-02 12:56
https://github.com/mumax/3/commit/8d67f79c50257e2c59c775e1a4a4451288de99e6

Please 'git pull origin master' or use 'Download ZIP' on the github page.
<https://github.com/mumax/3/commit/8d67f79c50257e2c59c775e1a4a4451288de99e6>

**Comment by oxishmit** [comment] 2015-11-04 02:42
Long Path Tool is best solution for long file names.

**Comment by barnex** [comment] 2015-11-07 20:13
@godsic: the *_53.ptx files are missing from this commit. Could you add them please? Also, I'd like to keep at least *_20.ptx and *_30.ptx unchanged (at language version 4.0, not 4.3) so people with old drivers can run something. I'd be glad to revert those files, but I need your 53.ptx to do that.

**Comment by godsic** [comment] 2015-11-07 21:03
@barne: oh fuck, sorry for breaking old ptx stuff and not attaching the new
once. Let me sort this out.

On 7 November 2015 at 21:13, Arne Vansteenkiste <notifications@github.com>
wrote:

> @godsic <https://github.com/godsic>: the *_53.ptx files are missing from
> this commit. Could you add them please? Also, I'd like to keep at least
> *_20.ptx and *_30.ptx unchanged (at language version 4.0, not 4.3) so
> people with old drivers can run something. I'd be glad to revert those
> files, but I need your 53.ptx to do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/51#issuecomment-154744311>.
>



-- 
 Mykola

**Comment by barnex** [comment] 2015-11-07 21:16
No worries, it's not like this made it into the release. We could probably use some testing or automation for this anyway, since I made the same mistake several times before.

**Comment by godsic** [comment] 2015-11-07 21:17
@barnex do you think it is legal to attach ptx files to the project? At the moment it is a bit hard to keep old/new ptx together behind the scenes. So it would be nice if you can commit the 3.9 ptx'es and then I will commit updated cc50, cc52 and cc53.

**Comment by barnex** [comment] 2015-11-07 21:23
@godsic: what exactly do you mean by 'legal'?
Anyway, I agree it is a pain to keep the ptx files checked in. We can probably experiment with not having them in the repo and see how that goes. But anyway the ptx content will still be inside .go files....

**Comment by godsic** [comment] 2015-11-07 21:28
@barnex Well Nvidia always has some strange licenses forbidding
distribution of things. The reason I've asked is that ptx are not
checked-in at the moment. So generating new wrappers relying on mixed ptx
versions is a bit problematic.

On 7 November 2015 at 22:23, Arne Vansteenkiste <notifications@github.com>
wrote:

> @godsic <https://github.com/godsic>: what exactly do you mean by 'legal'?
> Anyway, I agree it is a pain to keep the ptx files checked in. We can
> probably experiment with not having them in the repo and see how that goes.
> But anyway the ptx content will still be inside .go files....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/51#issuecomment-154752910>.
>



-- 
 Mykola

**Comment by barnex** [comment] 2015-11-07 21:33
Oh, sorry, I got confused there. Yeah, we can check-in our ptx files so we can collaboratively compile for a different cuda version. As far as I understand the cuda terms of use, this is legally OK. For the moment I only have nvcc 6.5, so I can only generate ptx 4.0. Having ptx 3.x would be nice though...

**Comment by godsic** [comment] 2015-11-07 21:43
shit I completely missed this commit https://github.com/mumax/3/commit/9e4efd8818638b2dc8afa908188e391b83140d94 So I will download 6.0 and sort things out myself.

**Comment by barnex** [comment] 2015-11-07 21:56
Cool, thanks. Keeping the older ptx versions around lets people with old
drivers (like me, because of steam) still enjoy mumax...

**Comment by godsic** [comment] 2015-11-07 22:01
Sure. Supercomputers and clusters are also quite conservative about
drivers. So I am planning to use cuda55 for cc2.0, cuda6.0 for cc3.0,
cuda6.5 for cc3.5 and cuda7.5 for 5.0, 5.2 and 5.3. Is it OK?

On 7 November 2015 at 22:56, Arne Vansteenkiste <notifications@github.com>
wrote:

> Cool, thanks. Keeping the older ptx versions around lets people with old
> drivers (like me, because of steam) still enjoy mumax...
>
> On Sat, 7 Nov 2015, 21:43 Mykola Dvornik <notifications@github.com> wrote:
>
> > shit I completely missed this commit 9e4efd8
> > <
> https://github.com/mumax/3/commit/9e4efd8818638b2dc8afa908188e391b83140d94
> >
> > So I will download 6.0 and sort things out myself.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mumax/3/issues/51#issuecomment-154753965>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumax/3/issues/51#issuecomment-154756813>.
>



-- 
 Mykola

**Comment by barnex** [comment] 2015-11-08 11:28
Sounds great, thanks! It's up to you whether or not we check in the PTX
files, I have no strong feelings about that.

**Comment by godsic** [comment] 2015-11-11 11:32
https://github.com/mumax/3/commit/9c790a884c33bb001220879c435b5d1075665fb9
https://github.com/mumax/3/commit/850daaa9d347d78ad0142a42c642d69521608fb4
https://github.com/mumax/3/commit/985edfc57b0ccd1127dd56d4dd3c35aacbeeb6a1
https://github.com/mumax/3/commit/a005263f323039d74709ac599e243a13c5169d68

**Closed by godsic** 2015-11-11 11:32 UTC
Labels: bug

**Comment by barnex** [comment] 2015-11-12 20:45
Nice, thanks @godsic!
