### ISSUE TITLE
mumax3 runtime error - "panic: runtime error: cgo argument has Go pointer to Go pointer"

### ISSUE THREAD

**Issue by skgumma** [mumax/3#72] opened 2016-08-10 03:40 UTC
I'm facing an error while running mumax3 code. I'm pretty new to mumax3 and not sure how to troubleshoot the issue. Appreciate any help regarding this issue. 

The content of mx3 file is:
setgridsize(256, 128, 1)
setcellsize(5e-9, 5e-9, 5e-9)

m = NeelSkyrmion(1,-1).scale(3,3,1)
saveas(m, "Néel_skyrmion")

The command executed is below
$ mumax3 mx3test.mx3
//mumax 3.9.1c linux_amd64 go1.6.2 (gc)
//CUDA 7050 Tesla K40t(11519MB) cc3.5, using CC35 PTX
//(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
//This is free software without any warranty. See license.txt
//output directory: /home/users/astar/dsi/anibal-g/scratch/neelSK.out/
//starting GUI at http://127.0.0.1:35367
setgridsize(256, 128, 1)
setcellsize(5e-9, 5e-9, 5e-9)
panic: runtime error: cgo argument has Go pointer to Go pointer
        panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x9d14a0, 0xc82119a460)
        /app/go/1.6.3/src/runtime/panic.go:481 +0x3e6
github.com/mumax/3/cuda/cu._cgoCheckPointer0(0x8b40e0, 0x10d77a0, 0x0, 0x0, 0x0, 0x8a5440)
        ??:0 +0x4d
github.com/mumax/3/cuda/cu.LaunchKernel(0x156ab60, 0x8, 0x1, 0x1, 0x200, 0x1, 0x1, 0x0, 0x0, 0x10d77a0, ...)
        /app/go/apps/src/github.com/mumax/3/cuda/cu/execution.go:22 +0x107
github.com/mumax/3/cuda.k_reducesum_async(0x2006200000, 0x2006300000, 0x2000000000, 0x8000, 0x10c1a80)
        /app/go/apps/src/github.com/mumax/3/cuda/reducesum_wrapper.go:59 +0x1c4
github.com/mumax/3/cuda.Sum(0xc8211e6050, 0xc8211e6050)
        /app/go/apps/src/github.com/mumax/3/cuda/reduce.go:22 +0xc4
github.com/mumax/3/engine.sAverageUniverse(0xc8212230e0, 0x0, 0x0, 0x0)
        /app/go/apps/src/github.com/mumax/3/engine/average.go:24 +0x247
github.com/mumax/3/engine.sAverageMagnet(0xc8212230e0, 0x0, 0x0, 0x0)
        /app/go/apps/src/github.com/mumax/3/engine/average.go:33 +0x75
github.com/mumax/3/engine.(_magnetization).average(0x10d5820, 0x0, 0x0, 0x0)
        /app/go/apps/src/github.com/mumax/3/engine/magnetization.go:31 +0x37
github.com/mumax/3/engine.(_comp).average(0xc8211bc020, 0x0, 0x0, 0x0)
        /app/go/apps/src/github.com/mumax/3/engine/comp.go:27 +0x52
github.com/mumax/3/engine.(_comp).Average(0xc8211bc020, 0x0)
        /app/go/apps/src/github.com/mumax/3/engine/comp.go:28 +0x24
github.com/mumax/3/engine.Close()
        /app/go/apps/src/github.com/mumax/3/engine/engine.go:42 +0x74
panic(0x9d14a0, 0xc82119a030)
        /app/go/1.6.3/src/runtime/panic.go:443 +0x4e9
github.com/mumax/3/cuda/cu._cgoCheckPointer0(0x8b40e0, 0x10d7988, 0x0, 0x0, 0x0, 0x8a5440)
        ??:0 +0x4d
github.com/mumax/3/cuda/cu.LaunchKernel(0x1619e70, 0x1, 0x40, 0x1, 0x200, 0x1, 0x1, 0x0, 0x0, 0x10d7988, ...)
        /app/go/apps/src/github.com/mumax/3/cuda/cu/execution.go:22 +0x107
github.com/mumax/3/cuda.k_normalize_async(0x2006200000, 0x2006220000, 0x2006240000, 0x0, 0x8000, 0xc8211f6030)
        /app/go/apps/src/github.com/mumax/3/cuda/normalize_wrapper.go:62 +0x20b
github.com/mumax/3/cuda.Normalize(0xc8212230e0, 0xc8211e6000)
        /app/go/apps/src/github.com/mumax/3/cuda/normalize.go:13 +0x145
github.com/mumax/3/engine.(_magnetization).normalize(0x10d5820)
        /app/go/apps/src/github.com/mumax/3/engine/magnetization.go:33 +0x4a
github.com/mumax/3/engine.(_magnetization).SetArray(0x10d5820, 0xc8212a4000)
        /app/go/apps/src/github.com/mumax/3/engine/magnetization.go:46 +0x154
github.com/mumax/3/engine.(_magnetization).SetInShape(0x10d5820, 0xb967b8, 0xc820145e30)
        /app/go/apps/src/github.com/mumax/3/engine/magnetization.go:108 +0x428
github.com/mumax/3/engine.(_magnetization).Set(0x10d5820, 0xc820145e30)
        /app/go/apps/src/github.com/mumax/3/engine/magnetization.go:51 +0x39
github.com/mumax/3/engine.(_magnetization).alloc(0x10d5820)
        /app/go/apps/src/github.com/mumax/3/engine/magnetization.go:38 +0xb1
github.com/mumax/3/engine.SetMesh(0x100, 0x80, 0x1, 0x3e35798ee2308c3a, 0x3e35798ee2308c3a, 0x3e35798ee2308c3a, 0x0, 0x0, 0x0)
        /app/go/apps/src/github.com/mumax/3/engine/mesh.go:46 +0x382
github.com/mumax/3/engine.SetCellSize(0x3e35798ee2308c3a, 0x3e35798ee2308c3a, 0x3e35798ee2308c3a)
        /app/go/apps/src/github.com/mumax/3/engine/mesh.go:105 +0x186
reflect.Value.call(0x96f040, 0xb965d8, 0x13, 0xa8c180, 0x4, 0xc821223090, 0x3, 0x3, 0x0, 0x0, ...)
        /app/go/1.6.3/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x96f040, 0xb965d8, 0x13, 0xc821223090, 0x3, 0x3, 0x0, 0x0, 0x0)
        /app/go/1.6.3/src/reflect/value.go:303 +0xb1
github.com/mumax/3/script.(*call).Eval(0xc8200241e0, 0x0, 0x0)
        /app/go/apps/src/github.com/mumax/3/script/call.go:61 +0x267
github.com/mumax/3/engine.EvalFile(0xc820024120)
        /app/go/apps/src/github.com/mumax/3/engine/script.go:95 +0x21b
main.runFileAndServe(0x7fffffffdeba, 0x31)
        /app/go/apps/src/github.com/mumax/3/cmd/mumax3/main.go:144 +0x1e5
main.main()
        /app/go/apps/src/github.com/mumax/3/cmd/mumax3/main.go:89 +0x35d

**Comment by barnex** [comment] 2016-08-10 08:08
Duplicate of #59, which has presumably been fixed. Did you compile this yourself? Off which branch? Which Go?

**Comment by barnex** [comment] 2017-09-20 16:09
Closing as #59 has long been fixed.

**Closed by barnex** 2017-09-20 16:09 UTC
